server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
    gateway:
      routes:
        - id: ticket
          uri: lb://ticket-service
          predicates:
            - Path=/api/ticket/**
        - id: member
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
