server:
  port: 8081
spring:
  application:
    name: member-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/railway
    username: root
    password: root
